name: Build

on:
  push:
    branches:
      - ci-improvements
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [17, 21]

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: |
            21-ea
            17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Checks
        run: ./gradlew check -PtoolchainVersion=${{ matrix.java }} --stacktrace
