name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 16]

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Run Build
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: build-jdk${{ matrix.java }}
          arguments: check --stacktrace
